### ISSUE TITLE
Enable NRT by default

### ISSUE THREAD

**Issue by andy840119** [karaoke-dev/karaoke#1390]
See how this issue did: https://github.com/ppy/osu/pull/18743/commits

We need to add this line in the `.csproj`, see this commit https://github.com/ppy/osu/pull/18743/commits/968640c95176f4a771ab6208234045f40e4ca281
```
<Nullable>enable</Nullable>
```

~~Also, notice that we will not add the `#nullable` in the `.cs` file. should fix all relative issue in the class.~~

And because it will be hard to fix it in a single PR, so might be separate into several parts:
- [x] `Beatmap` -> #1402 (except `KaraokeBeatmapResourcesProvider`)
- [x] `Bindables` -> #1404
- [x] `Config` -> #1401
- [x] `Difficulty` -> #1407
- [x] Edit
  - [x] Blueprint -> #1989
  - [x] Change handler -> #1419
  - [x] `Checkers` -> #1398
  - [x] Components -> #1989
  - [x] Configs -> #1989
  - [x] `Generator` -> #1399
  - [x] Import lyric -> #1989
  - [x] Lyrics -> #1989
    - [x] `Caret algorithm` -> #1395
    - [x]  `State` -> #1423
    - [x] Other -> #1989
  - [x] Setup -> #1989
  - [x] Singer -> #1989
  - [x] Translate -> #1989
  - [x] `Utils` -> #1989
- [x] `Extension` -> #1418
- [x] Graphic -> #2064
- [ ] `IO`
  - [x] `JsonSerializer` -> #1421 
- [x] `Judgement` -> #1403
- [x] `Localization` -> #1400
- [x] `Mods` -> #1397
- [x] `Objects` -> #1406
  - [ ] Drawable 
- [x] `Online` -> #1403
- [x] Overlays -> #1990
- [x] `Replay` -> #1405
- [x] `Scoring` -> #1403
- [ ] Screens
  - [ ] Edit
    - [x] Beatmaps -> #2003, #2010 and #2014
    - [ ] Components
    - [x] Import -> #2005
    - [x] Stages
  - [x] Settings -> #1994
  - [x] Skin -> #1996
- [x] `Skinning` -> #1412
- [x] Statistic -> #1992
- [x] `Timing` -> #1403
- [x] UI -> #1991
- [x] `Utils` -> #1408
- [x] `Root` -> #2041

In the test case:
- [x] `Helpers` -> #1409
- [x] `Resources` -> #1409

And notice that should apply in the test project also.
`Highlight` part means it's non-graphic and should be able to remove the `#nullable`

Note:
```bash
#!/bin/bash

for file in $( find "$@" -type f -name '*.cs' ); do
    # remove the nullable disable line generate in another script
    # install the brew install gnu-sed and use gsed instead of the sed commend.
    
    # see: https://unix.stackexchange.com/a/93909
    gsed -i 'N;/\n#nullable disable/d' "$file"
done
```
about the removing script

**Comment by andy840119** [comment]
Will trying to import in the https://github.com/karaoke-dev/osu-framework-font/issues/222 first.

**Comment by andy840119** [comment]
And note that https://github.com/karaoke-dev/LrcParser is using this flag as default.

see:
https://github.com/karaoke-dev/LrcParser/blob/main/LrcParser/LrcParser.csproj

**Comment by smoogipoo** [comment]
See https://github.com/ppy/osu-framework/pull/5241 for an automated script

**Comment by andy840119** [comment]
![image](https://user-images.githubusercontent.com/9100368/174420161-4d744b13-1b7f-4914-84f3-9dcd48947a06.png)
Seems some of the compile issue is related to the `ResolvedAttribute`.
Guess should wait until this issue solved.

Not really sure should mark this property as nullable because it will not be null after BDL.

**Comment by andy840119** [comment]
Or will use `null!` in o!f and lazer?
```
[Resolved]
private ILyricRubyTagsChangeHandler rubyTagsChangeHandler { get; set; } = null!;
```

**Comment by smoogipoo** [comment]
> Or will use `null!` in o!f and lazer?
> 
> ```
> [Resolved]
> private ILyricRubyTagsChangeHandler rubyTagsChangeHandler { get; set; } = null!;
> ```

Yep, this is the only workaround we have (for now? for ever?).

**Comment by andy840119** [comment]
![image](https://user-images.githubusercontent.com/9100368/174421110-5dae4a3c-dfd1-40e9-89bf-083c13b383dd.png)
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis
Not have deep looking about this but seems `AllowNullAttribute` works also.
Not really sure how to combine those two attributes, trying to solve this but got no answer.

**Comment by andy840119** [comment]
@smoogipoo A quick question:
Will `Children` or `InternalChildren` still accept null?
Like this one:
```
public IReadOnlyList<T>? Children
{
    get
    {
        if (Content != this)
            return Content.Children;

        return internalChildrenAsT;
    }
    set => ChildrenEnumerable = value;
}
```

Or will change to this one which only accept empty array?
```
public IReadOnlyList<T> Children
{
    get
    {
        return internalChildrenAsT;
    }
    set => ChildrenEnumerable = value;
}
```

**Comment by smoogipoo** [comment]
Will eventually be non-null only, the second one above.

**Comment by andy840119** [comment]
Man, this table did not update for a while.

**Comment by andy840119** [comment]
![image](https://github.com/karaoke-dev/karaoke/assets/9100368/f3dcecc1-8967-444b-8063-cb34fdebf8ce)
I think it's OK to close this issue because only has few nullable disable annotation in this project.
