### ISSUE TITLE
Learned from AegiSub.

### ISSUE THREAD

**Issue by andy840119** [karaoke-dev/karaoke#1593]
![image](https://user-images.githubusercontent.com/9100368/190668150-03a3239a-80c2-4a00-9775-ed4112513e21.png)
This is how AegiSub looks like.

![image](https://user-images.githubusercontent.com/9100368/190668384-d244e84e-5ced-4beb-bd10-b370190925a7.png)
This is what karaoke editor in the ruleset.

https://karaoke-dev.notion.site/Learned-from-AegiSub-78d7a25a6ad14c778fba11c2b8f71902
Notion is better for thinking and listing things, so list all the good point in the notion.

Here's the tutorial(chinese):
https://www.youtube.com/watch?v=x46-su3l6Gc&ab_channel=PAPAYA%E9%9B%BB%E8%85%A6%E6%95%99%E5%AE%A4

**Comment by Hexality** [comment]
oh btw, in aegisub after mapping the timing of the lyric line, you can use that map to split the line into multiple lines with each word.

**Comment by andy840119** [comment]
> oh btw, in aegisub after mapping the timing of the lyric line, you can use that map to split the line into multiple lines with each word.

@Hexality can you provide more detail about that (maybe screenshot or something)?
I cannot imagine ;_;

**Comment by Hexality** [comment]
https://hexality.fun/src/content/nWyFildTfh.mp4

**Comment by andy840119** [comment]
> https://hexality.fun/src/content/nWyFildTfh.mp4
Does that means it's able to playback with single part of separated lyric?

**Comment by andy840119** [comment]
Understand 🙆🏼‍♂️ 
But it's that a need to separate a lyric into multiple lyrics?

**Comment by andy840119** [comment]
BTW, cool theme!

**Comment by Hexality** [comment]
> Understand 🙆🏼‍♂️ But it's that a need to separate a lyric into multiple lyrics?

if you need precise timing only.

**Comment by andy840119** [comment]
![image](https://user-images.githubusercontent.com/9100368/192104831-b9712bdb-5dbc-4142-850e-0e9fa772d39f.png)
The new layout might looks like this 🎉 
Still have lots of adjustment but seems it's a nice start

**Comment by andy840119** [comment]
Guess this issue can be closed due to we already have #1595.
If something is great in the `AegiSub` and it will be a good idea to implement in here, open a new issue instead.

**Comment by andy840119** [comment]
![image](https://user-images.githubusercontent.com/9100368/202893267-170c5329-16d1-4ce9-ae80-0bfc20025a82.png)
Make a note about current progress.
