### ISSUE TITLE
Lyric display issue

### ISSUE THREAD

**Issue by U-siro** [karaoke-dev/karaoke#1641]
https://cdn.discordapp.com/attachments/1029074596000976928/1029074883088482374/osu_2022-10-11_01-51-57.mp4

for prevent copyright issue, I sent a beatmap file to discord @andy840119 
Two issues included :
- transition is canceled when they disappear too fast
- some lyrics are drawn over other one

**Comment by andy840119** [comment]
> transition is canceled when they disappear too fast

Haven't test on the translation for a while ;_;

> some lyrics are drawn over other one

it's a knows issue OHO. I remember current start time and end-time is being calculated by the lyric order and the time-tag.
But should let user able to edit it in the beatmap eventually.

**Comment by U-siro** [comment]
I mean transition, not translation.
I'm saying about when text is fading out, highlighting text is cancelled.
(video time: 0:40)
This song is very fast, so it caused this problem.

**Comment by U-siro** [comment]
This issue is solved. Please check some lyrics are drawn over other one!

**Comment by andy840119** [comment]
@U-siro guess this issue is solved after re-design the architecture for able to support different kinds of "stage".

see:
https://blog.karaoke.dev/changelog/2023.0507/

Feel free to open new issue if found anything weird(but i cannot guarantee fix the issue soom).
