### ISSUE TITLE
Fix not display lyric in singer editor.

### ISSUE THREAD

**Issue by andy840119** [karaoke-dev/karaoke#515]
This is the part of issue in #214 
Not really not sure why just using scrolling playfield with pooling like how mania do.
Need to make a check.

Also check is mania switch to pooling playfield?

**Comment by andy840119** [comment]
And move timeline by dragging is useful, but zooming might not so.

**Comment by andy840119** [comment]
Oops
Mania still not use pooling.

**Comment by smoogipoo** [comment]
Pooling for mania/support in scrolling ruleset is definitely on the list of things to be done soon :)

**Comment by andy840119** [comment]
See how #594 works.
Maybe not use hit object composer to handle lots of events?

**Comment by andy840119** [comment]
Fixed.
The only remaining thing is fixing sometimes scroll contains not sync position.

**Comment by andy840119** [comment]
This issue can be closed due to main issue has been fixed.
