### ISSUE TITLE
Setting karaoke config in customize page.

### ISSUE THREAD

**Issue by andy840119** [karaoke-dev/karaoke#529]
![image](https://user-images.githubusercontent.com/9100368/112741412-9dde0c80-8fc0-11eb-8a96-302acabde06c.png)
Because this ruleset cause too much space into here.
So might need  a space to handle config.
.
Not really sure how to place it
Maybe overlay or new screen with overlay(?), like how multiple player do?

**Comment by andy840119** [comment]
Also need to list all the main category:
- Style
  - Font: All, customize part and preview area
  - Cursor while playing
- Mode(will appear in V2), For now only setting scroll part.
  - Scrolling direction
  - Scrolling speed
  - Alternative text
- Saiten
  - Saiten device
  - Pitch
  - Vocal pitch
  - Saiten pitch
...

Will record in [notion](https://www.notion.so/Karaoke-config-category-dbfab8ff409e4d8cb64228317bab9410).

**Comment by vmfunc** [comment]
It's not possible to create your own category ? Instead of using an existing one

**Comment by andy840119** [comment]
It's impossible to create multi config category in origin small config area
So I need to create ruleset's own config page

**Comment by andy840119** [comment]
This issue can be closed due to base config has been implemented.
