### ISSUE TITLE
Add license 

### ISSUE THREAD

**Issue by andy840119** [karaoke-dev/karaoke#6]
Add license.
Mainly like : 
If any project use this project, should be open source also.

**Comment by Squiddu** [comment]
Not sure if that exists, but the closest is the [MIT License](https://tldrlegal.com/license/mit-license).

**Comment by andy840119** [comment]
Oops i used GPL license instead in #10

**Comment by Squiddu** [comment]
https://github.com/Luxiono/D.A.N.C.E/issues/1 Not sure if you care, but I'm not experienced in C# at all. I kinda do want some help with this project, but there's really nowhere else that this could be shown..

**Comment by andy840119** [comment]
You want to port DDR like [this video](https://www.youtube.com/watch?v=qKtkX_m62PA) using osu-framework or unity?
.
Also, it's better to open another issue instead of comment in closed issue.
It's easy to be ignored.
.
Or you can add my discord (andy840119) to discuss that.

**Comment by Squiddu** [comment]
what's the tag number for the Discord?

**Comment by andy840119** [comment]
andy840119#8457
