### ISSUE TITLE
Add details on how to play/import osu!karaoke in README

### ISSUE THREAD

**Issue by Squiddu** [karaoke-dev/karaoke#9]
Makes it easier for those not skilled in this stuff to play/use this.

**Comment by andy840119** [comment]
It's still beta, so create/import beatmap might be different in release version.
Or you can see list created beatmap in [here](https://github.com/osu-Karaoke/sample-beatmap/releases)

**Comment by Squiddu** [comment]
I was actually looking for a way to actually start PLAYING osu!karaoke. I feel like details need to be added to show how to download/setup the game itself, not beatmaps.

**Comment by andy840119** [comment]
If you just want to play the song :
1. Compile this project using visual studio.
2. Start the game.
3. Download beatmap [here](https://github.com/osu-Karaoke/sample-beatmap/releases)
4. Drag into game windows.

**Comment by andy840119** [comment]
https://github.com/osu-Karaoke/osu-karaoke-launcher

Launcher has been created.
you can follow readme to compile and run launcher 
And everything should be worked.
